# Source: jxboot-helmfile-resources/templates/ingress-config-configmap.yaml
apiVersion: v1
data:
  domain: "aa19521c473dd45e6a81bd67d8aae947-1004475246.us-west-2.elb.amazonaws.com"
  email: ""
  exposer: "Ingress"
  issuer: ""
  tls: "false"
kind: ConfigMap
metadata:
  name: ingress-config
  annotations:
    meta.helm.sh/release-name: 'jxboot-helmfile-resources'
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
